git:
  remote:
    upstream: 'mongodb/docs-compass'
    tools: 'mongodb/docs-tools'
project:
  name: 'compass'
  tag: 'compass'
  url: 'http://docs.mongodb.com/compass'
  title: "MongoDB Compass"
  branched: true
version:
  release: 'beta'
  branch: 'beta'
system:
  files:
    - 'intersphinx.yaml'
    - 'push.yaml'
    - 'integration.yaml'
    - 'sphinx_local.yaml'
    - htaccess: ['htaccess.yaml']
paths:
  output: 'build'
  source: 'source'
  includes: 'source/includes'
  images: 'source/images'
  tools: 'bin'
  buildsystem: 'build/docs-tools'
  builddata: 'config'
...
